spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: couponSystem-main
        uri: lb://couponSystem-main
        predicates:
        - Path=/couponSystem/**
        filters:
        - RewritePath=/couponSystem/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-main
            fallbackUri: forward:/fallback/couponSystem-main
      - id: couponSystem-admin
        uri: lb://couponSystem-admin
        predicates:
        - Path=/admin/**
        filters:
        - RewritePath=/admin/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-admin
            fallbackUri: forward:/fallback/couponSystem-admin
      - id: couponSystem-company
        uri: lb://couponSystem-company
        predicates:
        - Path=/company/**
        filters:
        - RewritePath=/company/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-company
            fallbackUri: forward:/fallback/couponSystem-company
      - id: couponSystem-customer
        uri: lb://couponSystem-customer
        predicates:
        - Path=/customer/**
        filters:
        - RewritePath=/customer/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-customer
            fallbackUri: forward:/fallback/couponSystem-customer
      - id: couponSystem-guest
        uri: lb://couponSystem-guest
        predicates:
        - Path=/guest/**
        filters:
        - RewritePath=/guest/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-guest
            fallbackUri: forward:/fallback/couponSystem-guest
      - id: MQActivityService
        uri: lb://activity
        predicates:
        - Path=/act/**
        filters:
        - RewritePath=/act/(?<segment>.*), /$\{segment} 
    consul:
      discovery:
        instanceId: Gateway
        health-check-interval: 5s
      config:
        management: 
          enabled: true
management:
  security: 
    enabled: false
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health
hystrix:
   dashboard:
       proxy-stream-allow-list: "*"
